In [1]:
import pandas as pd

# 2026-08-14: Camp Algebra

Camp Algebra held a competition in which campers were split into two teams: the Aces and the Ciphers. Various members of these teams competed in a triathlon of chess, basketball, and baseball. The results are shown below. To commemorate the event, the camp counselors designed a cuboidal trophy with dimensions that cleverly related to the results of the three events. Then, being Camp Algebra after all, they computed the square of the shortest path along the trophy’s surface from one corner to the opposite corner. After decoding that number, namely, what camp mascot did they carve into the trophy?

## Part 1 (Chess)

Occupatus, playing as white for the Aces, had Castor, playing as black for the Ciphers, on the ropes. But the industrious Castor clearly gave a dam. With what next move did Castor turn the tables?

In [23]:
df = pd.read_csv("data-chess.csv")
df

,X.1,Occupatus,Castor,X.2,Occupatus.1,Castor.1
0,1,d4,e5,13,exf6,gxf6
1,2,dxe5,Nc6,14,c3,a6
2,3,Nf3,Qe7,15,Nbd4,Qc4
3,4,Bf4,Qb4,16,Qc2,Nxd4
4,5,Bd2,Qxb2,17,Nxd4,d5
5,6,Nc3,f6,18,Nf5,Bxf5
6,7,Rb1,Qa3,19,Qxf5,h6
7,8,Nd5,Rb8,20,Bf4,Qxc3
8,9,Nxc7,Kd8,21,Bd2,Qd4
9,10,Nd5,Qxa2,22,Bf4,a5
10,11,Nc3,Qa3,23,Bxb8,a4
11,12,Nb5,Qc5,24,Rd1,"<span style=""background-color: #f7f088;"">???</..."

In [24]:
game = pd.concat([df["X.1"], df["X.2"]], ignore_index=True).to_frame(name="move")
game["occupatus"] = pd.concat([df["Occupatus"], df["Occupatus.1"]], ignore_index=True)
game["castor"] = pd.concat([df["Castor"], df["Castor.1"]], ignore_index=True)
game.loc[23, "castor"] = ''
game

    move occupatus castor
0      1        d4     e5
1      2      dxe5    Nc6
2      3       Nf3    Qe7
3      4       Bf4    Qb4
4      5       Bd2   Qxb2
5      6       Nc3     f6
6      7       Rb1    Qa3
7      8       Nd5    Rb8
8      9      Nxc7    Kd8
9     10       Nd5   Qxa2
10    11       Nc3    Qa3
11    12       Nb5    Qc5
12    13      exf6   gxf6
13    14        c3     a6
14    15      Nbd4    Qc4
15    16       Qc2   Nxd4
16    17      Nxd4     d5
17    18       Nf5   Bxf5
18    19      Qxf5     h6
19    20       Bf4   Qxc3
20    21       Bd2    Qd4
21    22       Bf4     a5
22    23      Bxb8     a4
23    24       Rd1

In [25]:
def write_pgn(df, filename):
    with open(filename, "w", encoding="utf-8") as fh:
        for row in df.itertuples():
            fh.write(f"{row.move}.{row.occupatus} {row.castor}\n")

write_pgn(game, "game.pgn")

Loading the PGN file into `xboard`, we get this:

![](game-position.png)

From here, the best move in [algebraic chess notation](https://en.wikipedia.org/wiki/Algebraic_notation_(chess)) is

    Bb4

which puts the white king in check and I believe forces a mate in 1 for black.

    24. --- Bb4+
    25. Rd2 Qxd2#

In [26]:
int("0xBb4", 16)

2996

## Part 2 (Basketball)

The Aces crushed the Ciphers in the second competition. While the box score showed all the players’ names in order, it neglected to tally the two teams’ scores bit by bit. (Statistics are minutes, rebounds, assists, steals, blocks, total field goals, 3-point field goals and free throws.)

In [28]:
df_bskt_aces = pd.read_csv("data-basketball-aces.csv")
df_bskt_aces['Team'] = 'Aces'
df_bskt_aces

               Name  Min  Reb  Ast  St  Blk   FG  3FG   FT  Team
0       Smith, Zero   38    5    2   1    0  5-9  2-4  1-2  Aces
1       Taylor, Nil   36    4    3   1    1  4-8  2-3  2-3  Aces
2       Allen, Void   35    6    1   2    0  4-9  1-3  3-5  Aces
3       Harris, Off   34    3    4   1    0  4-7  1-2  2-2  Aces
4      Ingram, Null   34    7    2   0    1  4-6  1-2  2-4  Aces
5  Robinson, Nought   34    5    3   1    0  4-7  2-4  1-2  Aces
6       Davis, Nada   29    4    2   2    0  3-6  1-2  3-4  Aces

In [29]:
df_bskt_cipher = pd.read_csv("data-basketball-ciphers.csv")
df_bskt_cipher['Team'] = 'Ciphers'
df_bskt_cipher

                 Name  Min  Reb  Ast  St  Blk    FG  3FG   FT     Team
0       Parker, Unity   36    6    4   2    1  8-14  2-4  2-2  Ciphers
1       Edwards, Solo   35    5    6   1    0  7-12  3-5  2-3  Ciphers
2  Roberts, Singleton   35    7    3   1    1  7-11  1-3  3-3  Ciphers
3       Foster, Primo   34    4    5   2    0  6-10  2-4  3-5  Ciphers
4          Ellis, Uno   34    3    7   2    1   6-9  2-3  4-4  Ciphers
5       Carter, Tally   34    8    2   1    2  6-10  3-5  3-4  Ciphers
6    Thompson, O'Neal   32    5    4   3    0  6-10  4-4  1-1  Ciphers

## Part 3 (Baseball)

In the final event, the Aces narrowly defeated the Ciphers, 5-4. But whatever did the scoreboard look like? Surely both line-ups had something to say about that.